export const establishmentSeed = [
    {
      "id": "uuid-baoba",
      "name": "Baobá",
      "id_type": "uuid-public-park",
      "description": "O Baobá é o lugar perfeito para relaxar e desfrutar de deliciosos coquetéis e petiscos. Venha nos visitar e aproveite nossa atmosfera acolhedora e música ao vivo todas as sextas-feiras!",
      "tag": "none",
      "address": "Rua da  Selva, 42",
      "id_sponsor": "uuid-oscar-neves",
      "created_at": "2020-01-02 03:00:00",
      "updated_at": "2020-02-27 03:00:00"
    },
    {
      "id": "uuid-casa-club",
      "name": "Casa Club",
      "id_type": "uuid-club",
      "description": "A Casa Club é o lugar perfeito para quem busca diversão e entretenimento. Com uma decoração moderna e sofisticada, oferecemos uma ampla variedade de bebidas e petiscos deliciosos. Venha curtir a noite conosco e aproveite nossas promoções especiais!",
      "tag": "none",
      "address": "Rua dos clubes, 45",
      "id_sponsor": "uuid-quiteria-machado",
      "created_at": "2020-01-23 03:00:00",
      "updated_at": "2020-02-26 03:00:00"
    },
    {
      "id": "uuid-centro-de-descobertas",
      "name": "Centro de descobertas",
      "id_type": "uuid-museum",
      "description": "O Centro de Descobertas é o lugar perfeito para explorar e aprender. Com uma variedade de atividades interativas e educativas, oferecemos uma experiência única para todas as idades. Venha descobrir conosco!",
      "tag": "none",
      "address": "Rua da descoberta, 32",
      "id_sponsor": "uuid-helena-ribeiro",
      "created_at": "2024-01-02 03:00:00",
      "updated_at": "2024-02-27 03:00:00"
    },
    {
      "id": "uuid-cinelandia",
      "name": "Cinelândia",
      "id_type": "uuid-cinema",
      "description": "O melhor ponto de encontro cultural no coração do Rio de Janeiro. Venha desfrutar de filmes, teatro e música em um ambiente acolhedor e sofisticado. Imperdível!",
      "tag": "none",
      "address": "Rua Dos Filmes, 324",
      "id_sponsor": "uuid-cesar-augusto",
      "created_at": "2020-01-02 03:00:00",
      "updated_at": "2020-01-04 03:00:00"
    },
    {
      "id": "uuid-fliperama",
      "name": "Fliperama",
      "id_type": "uuid-private-park",
      "description": "O Fliperama é o lugar perfeito para se divertir com amigos e família! Com nossas máquinas de jogos clássicos e modernos, você pode passar horas se divertindo. Além disso, oferecemos deliciosos lanches e bebidas para acompanhar sua diversão. Venha nos visitar e experimente a emoção do Fliperama!",
      "tag": "none",
      "address": "Avenida dos Jogos, 34",
      "id_sponsor": "uuid-livia-souza",
      "created_at": "2020-01-02 03:00:00",
      "updated_at": "2020-01-25 03:00:00"
    },
    {
      "id": "uuid-jardim-botanico-da-cidade",
      "name": "Jardim Botanico da Cidade",
      "id_type": "uuid-museum",
      "description": "O Jardim Botânico da Cidade é um refúgio encantador para os amantes da natureza. Com uma variedade deslumbrante de plantas e flores, este paraíso verde oferece tranquilidade e beleza em cada passo. Venha explorar e se maravilhar com a exuberância deste lugar único!",
      "tag": "none",
      "address": "Rodovia Luiz Gonzaga, 43",
      "id_sponsor": "uuid-jessica-lima",
      "created_at": "2020-01-20 03:00:00",
      "updated_at": "2020-03-14 03:00:00"
    },
    {
      "id": "uuid-jurassic-park-burguer",
      "name": "Jurassic Park Burguer",
      "id_type": "uuid-snack-bar",
      "description": "Adoramos o Tematica Jurassic Park Burguer! A comida era deliciosa e os hambúrgueres eram tão suculentos como os dinossauros! A decoração era incrível, nos sentimos como se estivéssemos realmente no parque. Os funcionários eram simpáticos e prestativos, tornando a nossa experiência ainda mais agradável. Com certeza voltaremos para mais aventuras gastronômicas pré-históricas!",
      "tag": "none",
      "address": "Rua das comidas, 43",
      "id_sponsor": "uuid-roberto-silveira",
      "created_at": "2020-03-02 03:00:00",
      "updated_at": "2020-04-25 03:00:00"
    },
    {
      "id": "uuid-lagoa-azul",
      "name": "Lagoa Azul",
      "id_type": "uuid-public-park",
      "description": "O paraíso na terra! A Lagoa Azul é o refúgio perfeito para relaxar e se reconectar com a natureza. Desfrute de águas cristalinas, areia branca e uma paisagem deslumbrante. Venha viver momentos inesquecíveis em nosso paraíso tropical!",
      "tag": "popular",
      "address": "Rua da Criança, 43",
      "id_sponsor": "uuid-ester-vieira",
      "created_at": "2020-03-02 03:00:00",
      "updated_at": "2020-04-03 03:00:00"
    },
    {
      "id": "uuid-museu-da-criaca",
      "name": "Museu da Criaça",
      "id_type": "uuid-museum",
      "description": "O Museu da Criança é o lugar perfeito para a diversão em família! Com diversas atividades interativas, as crianças podem aprender enquanto se divertem. Venha conhecer nossas exposições e se encantar com o mundo da imaginação.",
      "tag": "none",
      "address": "Rua da história, 11",
      "id_sponsor": "uuid-marcelo-pinto",
      "created_at": "2020-01-02 03:00:00",
      "updated_at": "2020-02-25 03:00:00"
    },
    {
      "id": "uuid-museu-das-artes",
      "name": "Museu das Artes",
      "id_type": "uuid-museum",
      "description": "O Museu das Artes é um lugar encantador que abriga uma vasta coleção de obras de arte. Venha explorar a história e a cultura através de exposições fascinantes. Desfrute de um ambiente acolhedor e descubra a beleza da arte em cada detalhe. Visite-nos e deixe-se inspirar!",
      "tag": "none",
      "address": "Rua do Cateiro, 211",
      "id_sponsor": "uuid-igor-campos",
      "created_at": "2023-01-02 03:00:00",
      "updated_at": "2023-02-16 03:00:00"
    },
    {
      "id": "uuid-museu-do-espaco",
      "name": "Museu do espaço",
      "id_type": "uuid-museum",
      "description": "O Museu do Espaço é o lugar perfeito para explorar o universo! Com exposições interativas e incríveis réplicas de naves espaciais, proporcionamos uma experiência única para os amantes da astronomia. Venha nos visitar e embarque nessa jornada fascinante pelo cosmos!",
      "tag": "advertising",
      "address": "Avenida da descoberta, 123",
      "id_sponsor": "uuid-bruno-gonzalez",
      "created_at": "2020-01-02 03:00:00",
      "updated_at": "2020-02-14 03:00:00"
    },
    {
      "id": "uuid-parque-da-crianca",
      "name": "Parque da Criança",
      "id_type": "uuid-public-park",
      "description": "O Parque da Criança é o lugar perfeito para a diversão em família! Com diversas opções de brinquedos e atividades, as crianças vão se divertir muito enquanto os pais relaxam em um ambiente seguro e agradável. Venha nos visitar e aproveite o melhor do lazer em família!",
      "tag": "popular",
      "address": "Rua Central, 32",
      "id_sponsor": "uuid-anita-oliveira",
      "created_at": "2020-01-02 03:00:00",
      "updated_at": "2020-01-07 03:00:00"
    },
    {
      "id": "uuid-parquemania",
      "name": "Parquemania",
      "id_type": "uuid-private-park",
      "description": "Parquemania - O melhor parque de diversões da cidade! Venha se divertir em nossos brinquedos radicais e aproveite nossas deliciosas opções gastronômicas. Uma experiência inesquecível para toda a família!",
      "tag": "none",
      "address": "Rua da Alegria, 123",
      "id_sponsor": "uuid-fabio-lopes",
      "created_at": "2020-01-02 03:00:00",
      "updated_at": "2020-02-14 03:00:00"
    },
    {
      "id": "uuid-picinic-da-sol",
      "name": "Picinic da Sol",
      "id_type": "uuid-public-park",
      "description": "O Picnic da Sol é o lugar perfeito para desfrutar de momentos ao ar livre. Com uma atmosfera acolhedora e uma variedade de opções de alimentos frescos e deliciosos, você vai se sentir em um verdadeiro paraíso gastronômico. Venha aproveitar o sol e saborear nossas delícias!",
      "tag": "none",
      "address": "Praça da Iluminação, centro",
      "id_sponsor": "uuid-nadia-correia",
      "created_at": "2020-01-02 03:00:00",
      "updated_at": "2020-02-05 03:00:00"
    },
    {
      "id": "uuid-piscinao-azul",
      "name": "Piscinão Azul",
      "id_type": "uuid-club",
      "description": "O Piscinão Azul é o lugar perfeito para relaxar e se refrescar. Com uma piscina cristalina e um ambiente acolhedor, oferecemos o melhor em entretenimento aquático. Venha nos visitar e desfrute de momentos inesquecíveis!",
      "tag": "advertising",
      "address": "Rua dos clubes, 32",
      "id_sponsor": "uuid-quiteria-machado",
      "created_at": "2020-01-23 03:00:00",
      "updated_at": "2020-02-26 03:00:00"
    },
    {
      "id": "uuid-pizzamania",
      "name": "Pizzamania",
      "id_type": "uuid-snack-bar",
      "description": "Venha experimentar as melhores pizzas da cidade! Com uma variedade de sabores irresistíveis e ingredientes frescos, a Pizzamania é o lugar perfeito para satisfazer seu desejo por pizza. Ambiente acolhedor e atendimento de primeira. Não perca tempo, faça sua reserva agora mesmo!",
      "tag": "none",
      "address": "Rua das comidas, 43",
      "id_sponsor": "uuid-silvia-penna",
      "created_at": "2020-01-01 03:00:00",
      "updated_at": "2020-01-22 03:00:00"
    },
    {
      "id": "uuid-rancho-alegre",
      "name": "Rancho Alegre",
      "id_type": "uuid-private-park",
      "description": "O Rancho Alegre é o lugar perfeito para desfrutar de deliciosas refeições caseiras. Com um ambiente acolhedor e atendimento impecável, oferecemos pratos tradicionais da culinária brasileira. Venha nos visitar e saborear o melhor da gastronomia em um ambiente familiar e aconchegante.",
      "tag": "none",
      "address": "Avenida do Rancho, 235",
      "id_sponsor": "uuid-paula-rodrigues",
      "created_at": "2020-01-20 03:00:00",
      "updated_at": "2020-01-22 03:00:00"
    },
    {
      "id": "uuid-restaurante-da-rose",
      "name": "Restaurante da Rose",
      "id_type": "uuid-restaurant",
      "description": "O Restaurante da Rose é o lugar perfeito para saborear pratos deliciosos e autênticos. Com um ambiente acolhedor e atendimento impecável, garantimos uma experiência gastronômica única. Venha nos visitar e desfrute de momentos inesquecíveis!",
      "tag": "none",
      "address": "Avenida dos Pratos, 123",
      "id_sponsor": "uuid-monica-gomes",
      "created_at": "2020-01-02 03:00:00",
      "updated_at": "2020-01-05 03:00:00"
    },
    {
      "id": "uuid-serra-dos-cavalos",
      "name": "Serra dos Cavalos",
      "id_type": "uuid-public-park",
      "description": "Venha conhecer a Serra dos Cavalos, o refúgio perfeito para os amantes da natureza. Desfrute de trilhas deslumbrantes, cachoeiras encantadoras e uma vista panorâmica de tirar o fôlego. Aventure-se nesse paraíso e viva momentos inesquecíveis.",
      "tag": "none",
      "address": "Trila ecológica do cavalo",
      "id_sponsor": "uuid-fabiana-mourão",
      "created_at": "2020-01-01 03:00:00",
      "updated_at": "2020-01-04 03:00:00"
    },
    {
      "id": "uuid-veneza-parque",
      "name": "Veneza Parque",
      "id_type": "uuid-private-park",
      "description": "O Veneza Parque é o lugar perfeito para se divertir em família. Com uma ampla variedade de atrações, como piscinas, toboáguas e áreas de lazer, garantimos momentos inesquecíveis. Venha nos visitar e aproveite o melhor do entretenimento!",
      "tag": "none",
      "address": "Rodovia das Águas, km 34",
      "id_sponsor": "uuid-gabriel-nascimento",
      "created_at": "2023-01-02 03:00:00",
      "updated_at": "2023-01-06 03:00:00"
    },
    {
      "id": "uuid-zoo-safari-a-dentro",
      "name": "Zoo Safari a Dentro",
      "id_type": "uuid-zoo",
      "description": "O Zoo Safari a Dentro é o lugar perfeito para se conectar com a natureza e os animais. Desfrute de uma experiência única e emocionante, onde você pode observar de perto diversas espécies em seu habitat natural. Venha nos visitar e viva momentos inesquecíveis!",
      "tag": "none",
      "address": "Avenida da Selva, 32",
      "id_sponsor": "uuid-daniel-fernandes",
      "created_at": "2020-01-23 03:00:00",
      "updated_at": "2020-01-29 03:00:00"
    }
  ]